In [2]:
import tkinter as tk
from tkinter import filedialog
from transformers import BertTokenizer, TFBertModel
import tensorflow as tf

# 加载预训练的BERT模型和分词器
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained('bert-base-uncased')

def extract_keywords():
    # 打开文件对话框，让用户选择要上传的文件
    file_path = filedialog.askopenfilename(filetypes=[("Text files", "*.txt")])
    
    # 读取用户选择的文件内容
    with open(file_path, 'r') as file:
        text = file.read()
    
    # 将文本数据转换为适合BERT模型输入的格式
    inputs = tokenizer(text, return_tensors='tf')

    # 输入文本数据到BERT模型中，获取模型的输出
    outputs = model(inputs)

    # 打印模型输出
    print(outputs)

    # 提取关键词
    # 这里我们简单地根据词频提取关键词
    # 实际上，你可以根据具体的需求选择其他方法来提取关键词，如基于注意力权重等
    word_ids = inputs['input_ids'][0]
    word_counts = {}
    for word_id in word_ids.numpy():
        word = tokenizer.convert_ids_to_tokens([word_id])[0]  # 将列表转换为字符串
        if word not in word_counts:
            word_counts[word] = 0
        word_counts[word] += 1

    # 按照词频降序排列关键词
    keywords = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)

    # 将提取的关键词结果显示在文本框中
    result_text.delete('1.0', tk.END)
    for keyword, count in keywords:
        result_text.insert(tk.END, f"{keyword}: {count}\n")

# 创建主窗口
root = tk.Tk()
root.title("关键词提取工具")

# 创建上传按钮
upload_button = tk.Button(root, text="上传文件", command=extract_keywords)
upload_button.pack(pady=10)

# 创建显示结果的文本框
result_text = tk.Text(root, height=20, width=50)
result_text.pack()

# 运行主循环
root.mainloop()


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 250, 768), dtype=float32, numpy=
array([[[-0.2595441 ,  0.2858107 ,  0.41499174, ..., -0.30843148,
          0.24720925, -0.10604259],
        [-0.50820345,  0.7404983 ,  0.32789943, ...,  0.04555668,
          0.11598842, -0.20656884],
        [-0.79639566,  1.0304568 ,  1.1744268 , ..., -0.2262923 ,
          0.06880926, -0.5066491 ],
        ...,
        [ 0.32039112,  0.39853722,  1.0205747 , ...,  0.48386496,
         -0.20098948, -0.645842  ],
        [ 0.20964718, -0.05275623,  1.1086462 , ...,  0.45008543,
          0.14892082, -0.54902595],
        [ 0.46080592,  0.4400713 ,  0.21642578, ..., -0.10328835,
         -0.17611825, -0.07378511]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.7225809 , -0.37579077, -0.14676191,  0.26911417, -0.282051  ,
         0.0239751 ,  0.14140601,  0.3236094 ,  0.12033673, -0.9998169 ,
         0.3432692 ,  0.24